services:
  postgres_IGMA_db:
    image: postgres
    container_name: postgres_IGMA_db
    restart: always
    ports:
      - 4457:5432
    env_file:
      - .env
    volumes:
      - IGMA_db:/var/lib/postgresql/data

  node_app:
    container_name: node_app
    build: .
    ports:
      - 4000:4000
    depends_on:
      - postgres_IGMA_db
    env_file:
      - .env

volumes:
  IGMA_db:
